# Generated by Django 4.2.23 on 2025-07-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influenceur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceur',
            name='email',
            field=models.EmailField(default='email@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
