# Generated by Django 4.2.23 on 2025-07-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influenceur', '0002_influenceur_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_creer_influenceurs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_payer_remises',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_valider_prospects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='peut_voir_statistiques',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('influenceur', 'Influenceur'), ('moderateur', 'Modérateur')], default='influenceur', max_length=20),
        ),
    ]
