# Generated by Django 4.2.23 on 2025-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influenceur', '0003_influenceur_date_derniere_connexion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceur',
            name='bloque_jusqu_a',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_modification_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='date_derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influenceur',
            name='nombre_tentatives_connexion',
            field=models.IntegerField(default=0),
        ),
    ]
