# Generated by Django 4.2.23 on 2025-07-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0002_prospect_phone_alter_prospect_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='phone',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
