# Generated by Django 4.2.23 on 2025-07-11 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prospect', '0003_alter_prospect_email_alter_prospect_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prospect',
            old_name='phone',
            new_name='telephone',
        ),
    ]
